import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: 
  [{type: 'autogenerated', dirName: '.'}],
  // {
  //   'Roblox Part 1: Launch Your Own Obby Game': ['Roblox-Part1/intro', 'Roblox-Part1/setup', 'Roblox-Part1/stage1', 'Roblox-Part1/stage2', 'Roblox-Part1/stage3', 'Roblox-Part1/stage4', 'Roblox-Part1/stage5', 'Roblox-Part1/stage6', 'Roblox-Part1/stage7', 'Roblox-Part1/stage8', 'Roblox-Part1/stage9', 'Roblox-Part1/stage10', ],
  // },
  
  // But you can create a sidebar manually

  // tutorialSidebar: [
  //   'tutorial-basics/Stage-1',
  //   {
  //     type: 'category',
  //     label: 'Stage 1',
  //     items: [
  //       'tutorial-basics/Stage-1',
  //     ],
  //   },
  // ],
};

export const robloxSidebar = [
  {
    'Roblox Part 1: Launch Your Own Obby Game': ['Roblox-Part1/intro', 'Roblox-Part1/setup', 'Roblox-Part1/stage1', 'Roblox-Part1/stage2', 'Roblox-Part1/stage3', 'Roblox-Part1/stage4', 'Roblox-Part1/stage5', 'Roblox-Part1/stage6', 'Roblox-Part1/stage7', 'Roblox-Part1/stage8', 'Roblox-Part1/stage9', 'Roblox-Part1/stage10', ],
  },
  {
    'Roblox Part 2: Launch Your Own Obby Game in VR': ['Roblox-Part2/intro', 'Roblox-Part2/setup', 'Roblox-Part2/stage1', 'Roblox-Part2/stage2', 'Roblox-Part2/stage3', 'Roblox-Part2/stage4', 'Roblox-Part2/stage5', 'Roblox-Part2/stage6', 'Roblox-Part2/stage7', 'Roblox-Part2/stage8', 'Roblox-Part2/stage9', 'Roblox-Part2/stage10', ],
  },
  {
    'Roblox Entrepreneur Part 1: Lua Coding and Game Scripting': ['Roblox-Entre1/intro', 'Roblox-Entre1/setup', 'Roblox-Entre1/stage1', 'Roblox-Entre1/stage2', 'Roblox-Entre1/stage3', 'Roblox-Entre1/stage4', 'Roblox-Entre1/stage5', 'Roblox-Entre1/stage6', 'Roblox-Entre1/stage7', 'Roblox-Entre1/stage8', 'Roblox-Entre1/stage9', 'Roblox-Entre1/stage10', ]
  },
  {
    'Roblox Entrepreneur Part 2: Imaginative Game Design': ['Roblox-Entre2/intro', 'Roblox-Entre2/setup', 'Roblox-Entre2/stage1', 'Roblox-Entre2/stage2', 'Roblox-Entre2/stage3', 'Roblox-Entre2/stage4', 'Roblox-Entre2/stage5', 'Roblox-Entre2/stage6', 'Roblox-Entre2/stage7', 'Roblox-Entre2/stage8', 'Roblox-Entre2/stage9', 'Roblox-Entre2/stage10', ]
  },
];

export const pythonSidebar = [
  {
    'Python Part 1: Python 101': ['Python-Part1/intro', ]
  },
];

export const roboticsSidebar = [
  {
    'Robotics Part 1: With Scratch and mBot': ['Robotics-Part1/intro'],
  },
];

export default sidebars;
